### ISSUE TITLE
 ImportError: cannot import name delayed

### ISSUE THREAD

**Issue by lghada** [zoj613/pyloras#38] opened 2022-10-06 21:21 UTC
When I use LORAS to resample the data, I receive an error stating that it cannot import name delayed even when I use pip to install delayed.

**Comment by zoj613** [comment] 2022-10-12 20:17
Hi @lghada, Thanks for the bug report. Could you please provide a minimal working example that reproduces the error you encounter. Please also provide the versions of `pyloras` and `imbalanced-learn` that you are using in your environment. This library does not explicitly make use of `joblib`, which i'm guessing is where the `delayed` object is coming from. Does insalling `joblib` in your environment help get rid of this import error?

**Comment by lghada** [comment] 2022-10-14 01:27
Hi Zoj613, Thank you for your email. I was planning to update the message on GitHub to indicate resolved issue. It appears that the issue is with the Azure run environment. When we executed the python script on Azure ML Designer, the Designer didn't link to the installed delayed package during runtime. However, when we transfered the code to notebook, it worked fine. We are using imbalanced-learn version 0.7.0, pyloras version 0.1.0b5, and delayed version 0.11.0b1. Best regards, Ghada Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: zoj613 ***@***.***> Date: 10/12/22  4:17 PM  (GMT-05:00) To: zoj613/pyloras ***@***.***> Cc: lghada ***@***.***>, Mention ***@***.***> Subject: Re: [zoj613/pyloras]  ImportError: cannot import name delayed (Issue #38) 
Hi @lghada, Thanks for the bug report. Could you please provide a minimal working example that reproduces the error you encounter. Please also provide the versions of pyloras and imbalanced-learn that you are using in your environment.

**Comment by zoj613** [comment] 2022-10-14 05:39
Okay, since the error was not related to `pyloras` then I will close this. Feel free to re-open should you run into a different issue.

**Closed as completed by zoj613** 2022-10-14 05:39 UTC

**Comment by lghada** [comment] 2022-10-14 12:37
Thank you! Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: zoj613 ***@***.***> Date: 10/14/22  1:40 AM  (GMT-05:00) To: zoj613/pyloras ***@***.***> Cc: lghada ***@***.***>, Mention ***@***.***> Subject: Re: [zoj613/pyloras]  ImportError: cannot import name delayed (Issue #38) 
Okay, since the error was not related to pyloras then I will close this. Feel free to re-open should you run into a different issue.
